DROP TABLE IF EXISTS users, items, bookings, comments, requests;

CREATE TABLE IF NOT EXISTS users(
    id bigint generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL
);
CREATE unique index if not exists user_email_unique ON users (email);

CREATE TABLE IF NOT EXISTS requests(
    id bigint generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(512) NOT NULL,
    user_id bigint REFERENCES users (id) ON DELETE CASCADE,
    created TIMESTAMP without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items(
    id bigint generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(512) NOT NULL,
    is_available boolean,
    user_id bigint REFERENCES users (id) ON DELETE CASCADE,
    request_id bigint REFERENCES requests (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings(
    id bigint generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id bigint REFERENCES items (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE CASCADE,
    status varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS comments(
    id bigint generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(512) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    item_id bigint REFERENCES items (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE CASCADE
);
